
name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0/6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: rowan-vr/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUSH_BRANCH_NAME: main
          SHOW_LINES_OF_CODE: true
          SYMBOL_VERSION: 3
